/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl */

#ifndef _Included_com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl
#define _Included_com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl
 * Method:    systemVoiceUp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl_systemVoiceUp
  (JNIEnv *, jobject);

/*
 * Class:     com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl
 * Method:    systemVoiceDown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl_systemVoiceDown
  (JNIEnv *, jobject);

/*
 * Class:     com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl
 * Method:    systemVoiceMute
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_kdyzm_gentleman_intelligentcontroller_nativeImpl_NativeImpl_systemVoiceMute
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
