/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class NativeImpl */

#ifndef _Included_NativeImpl
#define _Included_NativeImpl
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     NativeImpl
	* Method:    systemVoiceUp
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_NativeImpl_systemVoiceUp
		(JNIEnv *, jobject);

	/*
	* Class:     NativeImpl
	* Method:    systemVoiceDown
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_NativeImpl_systemVoiceDown
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
